services:
  db:
    image: mysql:8.0
    container_name: mysql_analisis_territorial
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: analisis_territorial
    command: --local-infile=1 --lower-case-table-names=1
    ports:
      - "3307:3306"
    volumes:
      - .:/csv-data:ro
      - mysql_data_analisis_territorial:/var/lib/mysql
volumes:
  mysql_data_analisis_territorial:
