version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_analisis_territorial
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: analisis_territorial
    ports:
      - "3306:3306"
    command: --local-infile=1
